flatManagement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from rest_framework.urlpatterns import format_suffix_patterns

from userPanel import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', auth_views.login, name='login'),
    path('getToken/', obtain_jwt_token),
    path('checkToken/',verify_jwt_token),
    path('logout/', auth_views.logout, name='logout'),
    path('userPanel/', include('userPanel.urls')),
    path('api/', include('userPanel.api.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

userPanel/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = {
    # JSON
    # login
    # grupy
    path('groupsOfItems/', views.groupList.as_view(), name='groupList'),
    # path('oneGroupsOfItems/<int:pk>/', views.singleOfGroup.as_view(), name='singleGroup'),
    # path('updateGroup/<int:pk>', views.updateGroup.as_view(), name='updateGroup'),
    path('deleteGroup/<int:pk>', views.deleteGroup.as_view(), name='deleteGroup'),
    # # itemy
    path('itemList/', views.itemList.as_view(), name='itemList'),
    path('postList/', views.postList.as_view(), name='postList'),
    path('userList/', views.userListView.as_view(), name='usersList'),
    # path('updateItem/<int:group>/<int:id>', views.updateItem.as_view(), name='updateItem'),
}

userPanel/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    # pomocnicze
    path('def/', views.leftSideDef, name="def"),
    path('', views.welPage, name="main"),
    # posty
    path('putPost/', views.putPost, name='putPost'),
    path('postCreate/', views.postCreate, name="postCreate"),
    path('post/', views.putPost, name="post"),
    path('postDelete/<int:id>', views.postDelete, name="postDelete"),
    # grupy i itemy
    path('itemGroups/', views.groupOfItmesView, name="groups"),
    path('groups/<int:id>/', views.detailOfGroup, name="detail"),
    path('addGroup/', views.addGroup, name="groupCreate"),
    path('itemGroups/groupDelete/<int:id>', views.groupDelete, name="groupDelete"),
    path('addItem/<int:id>', views.addItem, name="addItem"),
    path('deleteItem/<int:idG>/<int:idI>/', views.deleteItem, name="deleteItem"),
    path('plusItem/<int:idG>/<int:idI>/', views.addOneUnit, name="plusItem"),
    path('minusItem/<int:idG>/<int:idI>/', views.minusOneUnit, name="minusItem"),
    # grafiki
    path('schedule/', views.putSchedule, name="schedule"),
    path('addFlatMateQ/', views.faltMateListCreate, name="cerateFlatMateQ"),
    path('addSchedule/', views.scheduleCreate, name="cerateSchedule"),
    path('scheduleDelete/', views.scheduleDelete, name="scheduleDelete"),
    path('addFlatMates/', views.addFlateMates, name="addMate"),

]

userPanel/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.urls import reverse
import json
from django.contrib.auth.models import User


class groupsOfItems(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nameGroup = models.CharField(max_length=100)

    def __str__(self):
        return " " + self.nameGroup + " "


class commonItems(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nameItem = models.CharField(max_length=100)
    amount = models.IntegerField(null=True)

    group = models.ForeignKey(groupsOfItems, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.nameItem)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    title = models.CharField(max_length=100)

    updated = models.DateTimeField(auto_now_add=True, blank=True)

    # time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-updated"]


def __str__(self):
    return str(self.title)


# def get_absolute_url(self):
#     return reverse("posts:detail", kwargs={"id": self.id})


class flatMateQueue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    userQ = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)

    def listUsers(self):
        return self.userQ.split(',')

    def numberOfFlatMates(self):
        return self.userQ.split(',').__len__()


class schedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    queue = models.ForeignKey(flatMateQueue, on_delete=models.CASCADE, null=True)
    weeks = models.CharField(max_length=300)
    current = models.IntegerField(default=0)
    week = models.IntegerField(default=0)
    currentWeek = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)

    def listWeeks(self):
        return self.weeks.split(',')

    def listU(self):
        return self.queue.listUsers()

    def getCurrentWeek(self):
        return self.currentWeek

    def incCurrent(self):
        maxF = self.queue.numberOfFlatMates()
        listW = self.listWeeks()

        self.current += 1
        if self.current < maxF:
            self.currentWeek = listW[self.current]


class flatMates(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    surrname = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name + self.surrname)

userPanel/forms.py
from django import forms

from .models import Post, groupsOfItems, commonItems, schedule, flatMateQueue, flatMates


class updateFlatMatesWeb(forms.ModelForm):
    class Meta:
        model = flatMates
        fields = [
            "name",
            "surrname",
        ]


class updateScheduleWeb(forms.ModelForm):
    class Meta:
        model = schedule
        fields = [
            "name",
            "queue",
            "weeks",
        ]


class updateflatMateQWeb(forms.ModelForm):
    class Meta:
        model = flatMateQueue
        fields = [
            "name",
            "userQ",
        ]


class updatePostWeb(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content"
        ]


class updateGroupWeb(forms.ModelForm):
    class Meta:
        model = groupsOfItems
        fields = [
            "nameGroup"
        ]


class updateItemWeb(forms.ModelForm):
    class Meta:
        model = commonItems
        fields = [
            "nameItem",
            "amount"
        ]

userPanel/api/views.py
from rest_framework.generics import ListAPIView, UpdateAPIView, RetrieveAPIView, DestroyAPIView
from django.shortcuts import get_object_or_404
from userPanel.models import commonItems, groupsOfItems,Post
from userPanel.serializer import itemSeralizer, groupOfItemsSeralizer, userSerializer , postSerializer
from django.db.models import Q
from django.contrib.auth.models import User

from rest_framework import mixins

#test
class userListView(ListAPIView):
    serializer_class = userSerializer

    def get_queryset(self, *args, **kwargs):
        queryset = User.objects.all()
        username = self.request.query_params.get('username', None)
        if username is not None:
            queryset = queryset.filter(username=username)

        return queryset


# itemy
class itemList(ListAPIView):
    serializer_class = itemSeralizer

    def get_queryset(self, *args, **kwargs):
        queryset = commonItems.objects.all()
        group = self.request.query_params.get('id', None)

        if group is not None:
            queryset = queryset.filter(group=group)

        return queryset


# class updateItem(UpdateAPIView):
#     queryset = commonItems.objects.all()
#     serializer_class = itemSeralizer
#     lookup_field = 'id'
#

# grupy
class groupList(ListAPIView):
    serializer_class = groupOfItemsSeralizer

    def get_queryset(self, *args, **kwargs):
        queryset = groupsOfItems.objects.all()
        user = self.request.query_params.get('id', None)
        if user is not None:
            queryset = queryset.filter(user=user)

        return queryset


# class updateGroup(UpdateAPIView):
#    # queryset = groupsOfItems.objects.all()
#     serializer_class = groupOfItemsSeralizer

class postList(ListAPIView):
    serializer_class = postSerializer

    def get_queryset(self, *args, **kwargs):
        queryset = Post.objects.all()
        user = self.request.query_params.get('id', None)
        if user is not None:
            queryset = queryset.filter(user=user)

        return queryset

#
class deleteGroup(DestroyAPIView):
    queryset = groupsOfItems.objects.all()
    serializer_class = groupOfItemsSeralizer
# curl -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6InJvb20xIiwiZXhwIjoxNTI4NTc1Mjk0LCJlbWFpbCI6IiJ9.4YhUt4WUO-g4Dx0ftqRy_bqPOnVeevWCsgPsIildCDM" -d username="dr" http://212.182.24.41:8000/api/groupsOfItems/

userPanel/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, render_to_response

from .models import groupsOfItems, groupsOfItems
from .models import Post
from .models import flatMates, flatMateQueue

from .models import schedule

from .forms import updatePostWeb, updateFlatMatesWeb, updateGroupWeb, updateItemWeb, updateflatMateQWeb, \
    updateScheduleWeb
from django.contrib.auth.decorators import login_required

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny
from rest_framework.generics import ListAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView
from userPanel.serializer import groupOfItemsSeralizer, itemSeralizer, groupOfItemsSeralizer
# from .models import fiveWeeks
from userPanel.models import commonItems, groupsOfItems

import datetime


@login_required
def scheduleCreate(request):
    weeks = ""
    date = datetime.date.today()
    cW = ""

    startWeek = date - datetime.timedelta(date.weekday())
    endWeek = startWeek + datetime.timedelta(6)

    queueList = flatMateQueue.objects.filter(user=request.user)
    quLen = flatMateQueue.objects.first()
    q = flatMateQueue.numberOfFlatMates(quLen)

    t1 = startWeek.strftime("%d-%m")
    t2 = endWeek.strftime("%d-%m")
    weeks += t1
    weeks += " - "
    weeks += t2
    cW = weeks
    weeks += ","

    date = endWeek

    for i in range(0, q-1):
        startWeek = date - datetime.timedelta(0)
        endWeek = startWeek + datetime.timedelta(7)
        date = endWeek
        endWeek = endWeek - datetime.timedelta(0)
        startWeek = startWeek + datetime.timedelta(1)
        t1 = startWeek.strftime("%d-%m")
        t2 = endWeek.strftime("%d-%m")
        weeks += t1
        weeks += " - "
        weeks += t2
        if i != q-2:
            weeks += ","

    form = updateScheduleWeb(request.POST or None)

    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.currentWeek = cW
            instance.save()

    context = {
        "form": form,
        "weeks": weeks,
        "queueList": queueList,
        # "duration": duration,

    }

    return render(request, "userPanel/addschedule.html", context)


@login_required
def putSchedule(request):
    list = schedule.objects.filter(user=request.user)
    date = datetime.date.today()
    # startWeek = date - datetime.timedelta(date.weekday())
    # endWeek = startWeek + datetime.timedelta(6)

    today = date.strftime("%d")
    todayM = date.strftime("%m")
    for i in list:
        qL = i.queue.numberOfFlatMates()
        qCur = i.current
        curWeek = i.currentWeek
        curWeek = curWeek.split(' - ')
        end = curWeek[1].split('-')
        start = curWeek[0].split('-')
        endD = end[0]
        endM = end[1]
        startM = start[1]
        if qCur != qL:
            if endM == todayM:
                if endD < today:
                    i.incCurrent()
                    i.save()
        else:
            i.delete()

    #list = schedule.objects.filter(user=request.user)

    date = datetime.date.today()
    today = date.strftime("%d-%m")
    context = {
        "list": list,
        "day": today,
    }
    return render(request, "userPanel/schedule.html", context)


@login_required
def scheduleDelete(request, id):
    instance = get_object_or_404(schedule, id=id)
    instance.delete()
    return HttpResponse("ok")


@login_required
def faltMateListCreate(request):
    form = updateflatMateQWeb(request.POST or None)
    userList = flatMates.objects.filter(user=request.user)
    count = userList.count()
    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

    context = {
        "userList": userList,
        "form": form,
        "count": count,
    }

    return render(request, "userPanel/addListOfMates.html", context)


@login_required
def addFlateMates(request):
    form = updateFlatMatesWeb(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

    context = {
        "form": form,
    }

    return render(request, "userPanel/addFlatMates.html", context)


@login_required
def flatMateQDelete(request, id):
    instance = get_object_or_404(flatMateQueue, id=id)
    instance.delete()
    return HttpResponse("ok")


# posty
@login_required
def postCreate(request):
    form = updatePostWeb(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

    context = {
        "form": form,
    }

    return render(request, "userPanel/addPost.html", context)


@login_required
def putPost(request):
    queryset = Post.objects.filter(user=request.user)
    # paginator = Paginator(queryset_list, 25)  # Show 25 contacts per page
    #
    # page = request.GET.get('page')
    # queryset = paginator.get_page(page)
    #

    context = {'obj': queryset}

    return render(request, 'userPanel/index.html', context)


@login_required
def postDelete(request, id):
    instance = get_object_or_404(Post, pk=id)
    instance.delete()

    return redirect('/userPanel/putPost/')


# grupy
@login_required
def groupOfItmesView(request):
    allGroups = groupsOfItems.objects.filter(user=request.user)

    groupsLen = allGroups.__len__()
    groupsLen = groupsLen / 3
    context = {'allGroups': allGroups, 'len': groupsLen}

    return render(request, 'userPanel/groupListView.html', context)


@login_required
def detailOfGroup(request, id):
    group = get_object_or_404(groupsOfItems, pk=id)

    return render(request, 'userPanel/groupDetail.html', {'groupDetail': group, 'id': id})



@login_required
def addGroup(request):
    form = updateGroupWeb(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

    context = {
        "form": form,
    }

    return render(request, "userPanel/addGroup.html", context)

@login_required
def groupDelete(request, id):
    instance = get_object_or_404(groupsOfItems, id=id)
    instance.delete()
    return redirect('/userPanel/itemGroups/')


#items
@login_required
def addItem(request, id):
    form = updateItemWeb(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.group = get_object_or_404(groupsOfItems, pk=id)
            instance.save()

    context = {
        "form": form,
        "id": id
    }

    return render(request, "userPanel/addItem.html", context)

@login_required
def deleteItem(request, idI, idG):
    instance = get_object_or_404(commonItems, pk=idI)
    instance.delete()
    return redirect('/userPanel/groups/'+str(idG))

@login_required
def addOneUnit(requset,idI,idG):
    instance = get_object_or_404(commonItems,id=idI)
    instance.amount = instance.amount + 1
    instance.save()
    return redirect('/userPanel/groups/'+str(idG))

def minusOneUnit(requset,idI,idG):
    instance = get_object_or_404(commonItems,id=idI)
    if 0 < instance.amount:
        instance.amount = instance.amount - 1
    instance.save()
    return redirect('/userPanel/groups/' + str(idG))

# pomocnicza strona
@login_required
def leftSideDef(request):
    return render(request, 'userPanel/leftSideDef.html')
@login_required
def welPage(request):
    return render(request, 'userPanel/welcomPage.html')

# ----------------------------------V---------------------------------------------
# ---------------------------------VVV---------------------------------------------
# -------------------------------VVVVVVV--------------------------------------------
# ------------------------------VVVVVVVVVV------------------------------------------

templates/userPanel/addFlatMates.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-sm-offset-3">
        <form method="POST" action="" style="border: none;">
            {% csrf_token %}
            <label for="id_name">Imie:</label>
            <input class="form-control" type="text" name="name" maxlength="100" required="" id="id_name">
            <br>
            <label for="id_surrname">Nazwisko:</label>
            <input class="form-control" type="text" name="surrname" maxlength="100" required="" id="surrname">

            <br>
            <p>
                <button type="submit" class="btn btn-primary mb-2">Dodaj</button>
            </p>
        </form>
    </div>
</div>

{% endblock %}

templates/userPanel/addGroup.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-sm-offset-3">
        <form method="POST" action="" style="border: none;">
            {% csrf_token %}
            <label for="id_nameGroup">Nazwa Grupy:</label>
            <input class="form-control" type="text" name="nameGroup" maxlength="100" required="" id="id_nameGroup">

            <br>
            <p>
                <button type="submit" class="btn btn-primary mb-2">Dodaj</button>
            </p>
        </form>
    </div>
</div>
{% endblock %}

templates/userPanel/addItem.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-sm-offset-3">
        <form method="POST" action="" style="border: none;">
            {% csrf_token %}
            <label for="id_nameItem">Nazwa przedmiotu</label>
            <input class="form-control" type="text" name="nameItem" maxlength="100" required="" id="id_nameItem">
            <label for="id_amount">Ilość</label>
            <input class="form-control" type="number" name="amount" maxlength="100" required="" id="id_amount">
            <br>
            <p>
                <button type="submit" class="btn btn-primary mb-2"  onclick="conf()" >Dodaj</button>
            </p>
        </form>
    </div>
</div>
       {# TU MOZE GDZEIS SIE SYPAC TESTOWAC  bo JAVASCRIPT TU JEST !!!! #}
    <script>
        function conf() {

                window.location.reload(false);
        }
    </script>
{% endblock %}

templates/userPanel/addListOfMates.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-sm-6 col-sm-offset-3">
            {% for i in userList %}
                <p>
{#                <label for="do not"></label>#}
                    <select class="form-control" id="id{{ forloop.counter }}">
                        {% for i in userList %}
                            <option>{{ i.name }} - {{ i.surrname }}</option>
                        {% endfor %}
                    </select>
                </p>

            {% endfor %}
            <form method="POST" action="" style="border: none;">
                {% csrf_token %}
                <label for="id_name">Nazwa kolejki:</label><br>
                <input class="form-control" id="id_name"  name="name">
                <label for="id_userQ">Kolejka:</label><br>
                <textarea class="form-control"  id="id_userQ" cols="10" rows="1" name="userQ" readonly></textarea>
                <br>
            <p><button onclick="scal(event)" class="btn btn-primary mb-2">Generuj kolejke</button></p>
            <p> <button type="submit" class="btn btn-primary mb-2">Dodaj kolejke</button></p>
            <br>
            <br>
            </form>
        </div>
    </div>
    <script>
        function scal(event) {
            var num ={{ count }};
            var takeText;
            var i;
            var str = "";
            for (i = 1; i <= num; ++i) {
                takeText = document.getElementById("id" + i);
                str += takeText.options[takeText.selectedIndex].text;
                if (i != num)str += ",";
            }
            document.getElementById("id_userQ").innerText = str;
            event.preventDefault()
            // x.innerHTML = str;
        }
    </script>

{% endblock %}

templates/userPanel/addPost.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-sm-offset-3">
        <form method="POST" action="" style="border: none;">
            {% csrf_token %}

            <label for="id_title">Tytuł:</label>
            <input class="form-control" type="text" name="title" maxlength="100" required="" id="id_title">


            <label for="id_content">Treść</label><br>
            <textarea class="form-control" name="content" cols="40" rows="10" id="id_content"></textarea>
            <br>
            <p>
                <button type="submit" class="btn btn-primary mb-2">Opublikuj</button>
            </p>
        </form>
    </div>
</div>
{% endblock %}

templates/userPanel/addschedule.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-sm-6 col-sm-offset-3">

            <form method="POST" action="" style="border: none;">
                {% csrf_token %}
                <label for="id_name">Nazwa Planu</label><br>
                <input class="form-control" id="id_name"  name="name">
                <label for="id_queue">Kolejka:</label><br>
                <p>
                    <select  class="form-control"  id="id_queue" name="queue">
                        {% for i in queueList %}
                            <option value="{{ i.id }}" >{{ i }}</option>
                        {% endfor %}
                    </select>
                </p>
                <label for="id_weeks">Tygodnie</label><br>
                <textarea class="form-control" id="id_weeks" cols="10" rows="1" name="weeks">{{ weeks }}</textarea>
{#                <label for="id_duration">Tygodnie</label><br>#}
{#                <textarea class="form-control" id="id_duration" cols="10" rows="1" name="duration">{{ duration }}</textarea>#}
                <br>
{#            <p><button onclick="scal(event)" class="btn btn-primary mb-2">Generuj kolejke</button></p>#}
            <p> <button type="submit" class="btn btn-primary mb-2">Dodaj Plan</button></p>
            <br>
            <br>
            </form>
        </div>
    </div>
    <script>
        function scal(event) {
            var num ={{ count }};
            var takeText;
            var i;
            var str = "";
            for (i = 1; i <= num; ++i) {
                takeText = document.getElementById("id" + i);
                str += takeText.options[takeText.selectedIndex].text;
                if (i != num) str += ",";
            }
            document.getElementById("id_userQ").innerText = str;
            event.preventDefault()
            // x.innerHTML = str;
        }
    </script>

{% endblock %}

templates/userPanel/baseLeft.html
<!DOCTYPE html>
{% load static %}
{% if user.is_authenticated %}

    <html lang="pl">
    <head>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>


        <meta charset="UTF-8">
        <title>userPanel</title>

    </head>
    <body>
    {% block content %}

    {% endblock %}
    <!-- ################################################################################################# -->

    </body>
    </html>
{% else %}
    <p>
        Brak dostepu
    </p>
{% endif %}

templates/userPanel/groupDetail.html
{% extends 'userPanel/baseLeft.html' %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-sm-6 col-sm-offset-3">
            <a href="{% url 'addItem' id %}" class="btn btn-primary btn-block">Dodaj item</a>
            <br>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Ilość</th>
                    <th scope="col">Akcje</th>
                </tr>
                </thead>
                <tbody>
                {% for item in groupDetail.commonitems_set.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <th scope="row">{{ item.nameItem }}</th>
                        <th scope="row">{{ item.amount }}</th>
                        <th scope="row"><a href="{% url 'plusItem' id item.id %}" class="btn btn-outline-success btn-sm" style="margin-right: 5px" onclick="reload()"> + </a>
                            <a href="{% url 'minusItem' id item.id %}" class="btn btn-outline-secondary btn-sm" style="margin-right: 15px" onclick="reload()"> - </a>
                            <a href="#" class="btn btn-outline-danger btn-sm" onclick="conf({{ id }},{{ item.id }})">Usuń</a></th>
                    </tr>
                {% endfor %}
            </table>
            <br>

        </div>
    </div>
    <script>
        function reload() {

            window.location.reload();
        }

        function conf(idG, idI) {
            var r = confirm("Czy napewno?");
            if (r == true) {
                window.location.href = '{{ '/userPanel/deleteItem/'}}' + idG +'/'+ idI ;
            } else {

            }
        }
    </script>
{% endblock %}

templates/userPanel/groupListView.html
{% extends 'userPanel/base.html' %}
{% block content %}
    <div class="container-fluid pt-4">
        <div class="row">
            <div class="col-md">
                <div class="container">
                    <div class="row" style="width: auto; word-wrap: break-word; margin: 5px">
                        {% for group  in  allGroups %}

                            <div class="card" style="margin: 10px; width: 13em">
                                <a href="{% url 'detail'  group.id %}"
                                   class="btn btn-primary btn-block" target="leftSide">{{ group.nameGroup }}</a>
                                <a href="#" onclick="conf({{ group.id }})" style="text-align: center">Usuń</a>
                            </div>


                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-md border-left"> <!-- prawo grafiki  -->
                <iframe src="{% url 'def' %}" name="leftSide"
                        style=" min-height:500px;width: 100%;height: 100%;overflow: hidden;"
                        frameborder="0"></iframe>
            </div>

        </div>
    </div>
    {# TU MOZE GDZEIS SIE SYPAC TESTOWAC  bo JAVASCRIPT TU JEST !!!! #}
    <script>
        function conf(id) {
            var r = confirm("Czy napewno chcesz usunąć tą grupę?");
            if (r == true) {
                window.location.href = '{{ './groupDelete/'}}' + id;
            } else {

            }
        }
    </script>
{% endblock %}